---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3250052534-fqD4m98QywsOIwqR25ZpdK0meEEze4dRNDKE4q1
:access_token_secret: WLXspTZ8ywe5mJXj8uXW4UMHgqAVHCKael2fkIFOaMhDS
